config/routes.rb
Rails.application.routes.draw do

  resources :markets
  resources :countries
  resources :companies do
    resources :historical_data do
      get 'list', on: :collection
      get 'prices', on: :collection
    end

    get 'list', on: :collection
  end
  resources :industries do
    get 'companies_ratio', on: :collection
  end
  resources :sectors do
    get 'companies_ratio'
    get 'companies_ratio', on: :collection
  end

  root 'companies#index'

end

app/models/industry.rb
class Industry < ActiveRecord::Base
  belongs_to :sector
  has_many :companies

  validates :name, :sector, presence: true

  def sector_name
    sector.name
  end

end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: [:show, :edit, :update, :destroy]

  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.includes(:sector, :companies)
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
  end

  def companies_ratio
    industries = Company.joins(:industry).where("industries.name != 'n/a'").group('industries.name').having('count(*) > ?', 40).count

    respond_to do |format|
      format.json { render json:  industries.sort_by {|_, v| v}.map { |k, v| {name: k, y: v} } }
    end
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industries/1
  # PATCH/PUT /industries/1.json
  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry.destroy
    respond_to do |format|
      format.html { redirect_to industries_url, notice: 'Industry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def industry_params
      params.require(:industry).permit(:name, :sector_id)
    end
end

app/views/industries/_form.html.haml
= form_for(industry) do |f|
  - if industry.errors.any?
    #error_explanation
      %h2
        = pluralize(industry.errors.count, "error")
        prohibited this industry from being saved:
      %ul
        - industry.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :sector_id
    %br/
    = f.text_field :sector_id
  .actions
    = f.submit

app/views/industries/_industry.html.haml
%tr
  %td= industry.name
  %td= industry.companies.size
  %td= link_to 'Show', industry
  %td= link_to 'Edit', edit_industry_path(industry)

app/views/industries/_list.html.haml
.element-container
  .title
    %span Industries
    %span.small= link_to 'all', industries_path
  .content
    %table.table
      %thead
        %tr
          %th Name
          %th Companies
          %th{:colspan => "3"}
      %tbody
        = render :partial => 'industries/industry', :collection => industries

app/views/industries/edit.html.haml
%h1 Editing Industry
= render 'form', industry: @industry
= link_to 'Show', @industry
|
= link_to 'Back', industries_path

app/views/industries/index.html.haml
.row
  .col-md-12
    .element-container
      #industry_chart{'data-url' => '/industries/companies_ratio'}
.row
  .col-md-6
    = render 'list', :industries => @industries

app/views/industries/new.html.haml
%h1 New Industry
= render 'form', industry: @industry
= link_to 'Back', industries_path

app/views/industries/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @industry.name
%p
  %strong Sector:
  = @industry.sector_name
= link_to 'Edit', edit_industry_path(@industry)
|
= link_to 'Back', industries_path