config/routes.rb
Rails.application.routes.draw do

  resources :markets
  resources :countries
  resources :companies do
    resources :historical_data do
      get 'list', on: :collection
      get 'prices', on: :collection
    end

    get 'list', on: :collection
  end
  resources :industries do
    get 'companies_ratio', on: :collection
  end
  resources :sectors do
    get 'companies_ratio'
    get 'companies_ratio', on: :collection
  end

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :industry
  has_one :sector, :through => :industry
  has_many :historical_data
  has_many :subsidiaries_mergers, :class_name => 'Merger', :foreign_key => :acquiring_id
  has_one :parent_merger, :class_name => 'Merger', :foreign_key => :acquired_id
  has_one :parent, :through => :parent_merger, :source => :acquiring
  has_many :subsidiaries, :through => :subsidiaries_mergers, :source => :acquired
  has_one :companies_changes_from, :class_name => 'CompaniesChange', :foreign_key => :from_id
  has_one :became, :through => :companies_changes_from, :source => :to
  has_one :companies_changes_to, :class_name => 'CompaniesChange', :foreign_key => :to_id
  has_one :was, :through => :companies_changes_to, :source => :from

  validates :industry, :name, :symbol, presence: true

  def industry_name
    industry.name
  end

  def sector_name
    sector.name
  end

  def sector_id
    sector.id
  end

  def latest_historical_data
    historical_data.order('trade_date desc').limit(1)
  end

  def to_json
    {
        :id => id,
        :symbol => symbol,
        :name => name,
        :industry => industry.name,
        :sector => sector.name,
        :industry_id => industry_id,
        :sector_id => sector.id,
        :delisted => delisted,
        :inactive => !active,
        :liquidated => liquidated,
        :merged => merged?,
        :changed => became.present?,
        :details => details
    }
  end

  def merged?
    parent.present?
  end

  def details
    merger_msg.to_s + changes_msg.to_s + liquidated_msg.to_s + delisted_msg.to_s
  end

  def merger_msg
    msg = ''
    if parent.present?
      msg << "acquired by #{parent.name}"
    end
    if subsidiaries.present?
      msg << "subsidiaries: #{subsidiaries.map(&:name).join(', ')}"
    end
    msg
  end

  def changes_msg
    "became #{became.name}" if became.present?
  end

  def liquidated_msg
    'liquidated' if liquidated
  end

  def delisted_msg
    'delisted' if delisted
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_filter(only: :list) { sanitize_order_params([Company, Industry, Sector]) }

  # GET /companies
  # GET /companies.json
  def index
  end

  def list
    @companies = Company.includes([:industry, :sector, :parent, :subsidiaries, :became])
                     .order("#{@sort || 'companies.name'} #{@order}")
                     .limit(params[:limit])
                     .offset(params[:offset])
    search = params[:search]
    if search.present?
      @companies = @companies
                       .joins([:industry, :sector])
                       .where('industries.name ~* ? OR sectors.name ~* ? OR companies.name ~* ? OR lower(companies.symbol) = lower(?)',
                              search, search, search, search)
      @count = Company
                   .joins([:industry, :sector])
                   .where('industries.name ~* ? OR sectors.name ~* ? OR companies.name ~* ? OR lower(companies.symbol) = lower(?)',
                          search, search, search, search)
                    .count
    else
      @count = Company.count
    end
    respond_to do |format|
      format.json { render json: { :total => @count,
                                   :rows => @companies.map(&:to_json) } }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :industry_id, :symbol)
    end
end

app/views/companies/_form.html.haml
= form_for(company) do |f|
  - if company.errors.any?
    #error_explanation
      %h2
        = pluralize(company.errors.count, "error")
        prohibited this company from being saved:
      %ul
        - company.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :industry_id
    %br/
    = f.text_field :industry_id
  .field
    = f.label :symbol
    %br/
    = f.text_field :symbol
  .actions
    = f.submit

app/views/companies/edit.html.haml
%h1 Editing Company
= render 'form', company: @company
= link_to 'Show', @company
|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 List of companies

.company-legend
  .legend-scale
    %ul.legend-labels
      %li
        %span.company-delisted
        Delisted
      %li
        %span.company-liquidated
        Liquidated
      %li
        %span.company-merged
        Merged
      %li
        %span.company-changed
        Changed name or symbol

%table#companies_table.table-striped{'data-pagination' => 'true',
             'data-page-list' => '[10, 25, 50, 100, 200, 500]',
             'data-search' => 'true',
             'data-side-pagination' => 'server',
             'data-url' => "/companies/list"}
= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New Company
= render 'form', company: @company
= link_to 'Back', companies_path

app/views/companies/show.html.haml
= link_to 'Back', companies_path
.row
  .col-md-5
    .element-container
      .title Company
      .content
        %p#notice= notice
        %p
          %strong Name:
          = raw @company.name
        %p
          %strong Sector:
          = link_to @company.sector_name, sector_path(@company.sector_id)
        %p
          %strong industry:
          = link_to @company.industry_name, industry_path(@company.industry_id)
        %p
          %strong Symbol:
          = @company.symbol
        - if @company.details.present?
          %p
            %strong Details:
            = @company.details
  .col-md-7
    .element-container
      .title Key Statistics
      .content
.row
  .col-md-12
    .element-container
      .title Historical Prices
      .content
        #company_chart{'data-url' => "/companies/#{@company.id}/historical_data/prices?n_days=365",
                       'data-name' => @company.name }

.row
  .col-md-12
    .element-container
      .title Historical Prices
      .content
        %table#historical_prices_table.table-striped{'data-pagination' => 'true',
                   'data-page-list' => '[10, 25, 50, 100, 200, 500]',
                   'data-side-pagination' => 'server',
                   'data-url' => "/companies/#{@company.id}/historical_data/list"}

= link_to 'Back', companies_path