config/routes.rb
Rails.application.routes.draw do

  resources :markets
  resources :countries
  resources :companies do
    resources :historical_data do
      get 'list', on: :collection
      get 'prices', on: :collection
    end

    get 'list', on: :collection
  end
  resources :industries do
    get 'companies_ratio', on: :collection
  end
  resources :sectors do
    get 'companies_ratio'
    get 'companies_ratio', on: :collection
  end

  root 'companies#index'

end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, :code, presence: true
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :code)
    end
end

app/views/countries/_form.html.haml
= form_for(country) do |f|
  - if country.errors.any?
    #error_explanation
      %h2
        = pluralize(country.errors.count, "error")
        prohibited this country from being saved:
      %ul
        - country.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :code
    %br/
    = f.text_field :code
  .actions
    = f.submit

app/views/countries/edit.html.haml
%h1 Editing Country
= render 'form', country: @country
= link_to 'Show', @country
|
= link_to 'Back', countries_path

app/views/countries/index.html.haml
%p#notice= notice
%h1 Listing Countries
%table
  %thead
    %tr
      %th Name
      %th Code
      %th{:colspan => "3"}
  %tbody
    - @countries.each do |country|
      %tr
        %td= country.name
        %td= country.code
        %td= link_to 'Show', country
        %td= link_to 'Edit', edit_country_path(country)
        %td= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Country', new_country_path

app/views/countries/new.html.haml
%h1 New Country
= render 'form', country: @country
= link_to 'Back', countries_path

app/views/countries/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @country.name
%p
  %strong Code:
  = @country.code
= link_to 'Edit', edit_country_path(@country)
|
= link_to 'Back', countries_path