config/routes.rb
Rails.application.routes.draw do

  resources :markets
  resources :countries
  resources :companies do
    resources :historical_data do
      get 'list', on: :collection
      get 'prices', on: :collection
    end

    get 'list', on: :collection
  end
  resources :industries do
    get 'companies_ratio', on: :collection
  end
  resources :sectors do
    get 'companies_ratio'
    get 'companies_ratio', on: :collection
  end

  root 'companies#index'

end

app/models/market.rb
class Market < ActiveRecord::Base
  belongs_to :country

  validates :name, :country, presence: true

  def country_name
    country.name
  end

  def country_code
    country.code
  end

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.all
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to markets_url, notice: 'Market was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:name, :country_id)
    end
end

app/views/markets/_form.html.haml
= form_for(market) do |f|
  - if market.errors.any?
    #error_explanation
      %h2
        = pluralize(market.errors.count, "error")
        prohibited this market from being saved:
      %ul
        - market.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :country_id
    %br/
    = f.text_field :country_id
  .actions
    = f.submit

app/views/markets/edit.html.haml
%h1 Editing Market
= render 'form', market: @market
= link_to 'Show', @market
|
= link_to 'Back', markets_path

app/views/markets/index.html.haml
%p#notice= notice
%h1 Listing Markets
%table
  %thead
    %tr
      %th Name
      %th Country
      %th{:colspan => "3"}
  %tbody
    - @markets.each do |market|
      %tr
        %td= market.name
        %td= market.country_name
        %td= link_to 'Show', market
        %td= link_to 'Edit', edit_market_path(market)
        %td= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Market', new_market_path

app/views/markets/new.html.haml
%h1 New Market
= render 'form', market: @market
= link_to 'Back', markets_path

app/views/markets/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @market.name
%p
  %strong Country:
  = @market.country_name
= link_to 'Edit', edit_market_path(@market)
|
= link_to 'Back', markets_path